### PR TITLE
Repo Cleanup

### PR DESCRIPTION
**Pull request by jdorfman**
Added: 
- License
- Contributing
- Minified CSS
- Integrity hash in `index.html` code block

Updated:
- `index.html`
- CSS (license and minified)

To do before go live:
- Setup CDN
- Logo
- Favicon
- Check/fix links

### CODE REVIEW

**Comment by fontfamous** [comment]
Awesome work Justin, thanks so much!

**Comment by fontfamous** [comment]
Hey Justin, how are you.

The Font Famous project never really took off how I thought it might, but there are some folks who still use it.

I noticed maxcdn was no longer working.

What do you think? Is there another option that you'd suggest? I'd like to keep it up for the folks who seem to be using it.

Ideas?

Hope you are well! I really loved your 
mentorship and help getting it going.

A

**Comment by jdorfman** [comment]
Hey Anthony,

I no longer work for MaxCDN so I would highly recommend promoting the link with RawGit. 

```
<link rel="stylesheet" href="https://cdn.rawgit.com/fontfamous/fontfamous.github.io/master/public/1.0.0/css/font-famous.min.css" integrity="sha384-OBbXwb7VdVBrsf6KLcK+mIo+dcI0i8fSwl2r7NQFv+EYIPmtksZXP9IPOOqF0vsE" crossorigin="anonymous">
```

🤘

**Comment by fontfamous** [comment]
Thanks man!

**Pull request merged**
